---
- name: Removing superfluous packages
  become: yes
  ansible.builtin.dnf:
    name: "{{ superfluous_el9_pkgs }}"
    autoremove: true
    state: absent

- name: Adding RPM repositories
  block:
  - name: Adding EPEL repository
    become: yes
    ansible.builtin.dnf:
      name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
      disable_gpg_check: true
      state: present
    when: desired_el9_pkgs | intersect(epel) | length
  - name: Adding CRB repository
    become: yes
    community.general.ini_file:
      path: "{{ (ansible_distribution == 'AlmaLinux') | ternary('/etc/yum.repos.d/almalinux-crb.repo', (ansible_distribution == 'Rocky' | ternary('/etc/yum.repos.d/rocky.repo', ''))) }}"
      section: crb
      option: enabled
      value: 1
      create: false
    when: desired_el9_pkgs | intersect(crb) | length
  - name: Adding RPM Fusion Free repository
    become: yes
    ansible.builtin.dnf:
      name: "https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      disable_gpg_check: true
      state: present
    when: desired_el9_pkgs | intersect(rpmfusion_free_el9) | length
  - name: Adding RPM Fusion Nonfree repository
    become: yes
    ansible.builtin.dnf:
      name: "https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      disable_gpg_check: true
      state: present
    when: desired_el9_pkgs | intersect(rpmfusion_nonfree_el9) | length
  - name: Adding Visual Studio Code repository
    become: yes
    ansible.builtin.yum_repository:
      name: vscode
      description: Visual Studio Code
      baseurl: https://packages.microsoft.com/yumrepos/vscode
      enabled: true
      gpgcheck: true
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    when: desired_el9_pkgs | intersect(vscode) | length
  - name: Adding Yandex.Disk repository
    become: yes
    ansible.builtin.yum_repository:
      name: yandex-disk
      description: Yandex.Disk
      baseurl: http://repo.yandex.ru/yandex-disk/rpm/stable/$basearch
      enabled: true
      failovermethod: priority
      gpgcheck: false # TODO sha-1 depricated
      gpgkey: http://repo.yandex.ru/yandex-disk/YANDEX-DISK-KEY.GPG
      metadata_expire: 1d
    when: desired_el9_pkgs | intersect(yandex_disk) | length

- name: Updating existing packages
  become: yes
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Installing desired packages
  become: yes
  ansible.builtin.package:
    name: "{{ desired_el9_pkgs }}"
    state: latest
