---
- name: Adding flathub remote
  become: yes
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present

- name: Installing desired flatpaks
  community.general.flatpak:
    name: "{{ flatpak_packages }}"
    remote: flathub
    state: present
