---
# TODO reorganize software role
- name: Installing CentOS epel-release
  become: yes
  ansible.builtin.dnf:
    name: epel-release
    disable_gpg_check: false
    state: present
  when: ansible_distribution == "CentOS"

- name: Adding RPM Fusion repositories
    become: yes
    ansible.builtin.dnf:
      name:
        - "https://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        # - "https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      disable_gpg_check: true
      state: present
    when: ansible_distribution == "CentOS"

- name: Installing software on Red Hat family operating system
  ansible.builtin.include_tasks: fedora.yml
  when: ansible_os_family == "RedHat"

- name: Installing flatpaks
  ansible.builtin.include_tasks: flatpak.yml
