---
- name: Installing software on RedHat family operation system
  block:
  - name: Installing software on Enterprise Linux 9
    ansible.builtin.include_tasks: enterprise9.yml
    when: (ansible_distribution == "AlmaLinux" or ansible_distribution == "Rocky") and ansible_distribution_major_version == "9"
  when: ansible_os_family == "RedHat"

- name: Installing flatpaks
  ansible.builtin.include_tasks: flatpak.yml
