---
- name: Installing software on Red Hat family operation system
  block:
  - name: Installing software on Rocky Linux
    ansible.builtin.include_tasks: rocky.yml
    when: ansible_distribution == "Rocky"
  - name: Installing software on Fedora Workstation
    ansible.builtin.include_tasks: fedora.yml
    when: ansible_distribution == "Fedora"
  when: ansible_os_family == "RedHat"

# - name: Installing flatpaks
#   ansible.builtin.include_tasks: flatpak.yml
