---
superfluous_el9_pkgs:
  - brasero
  - cheese
  - evolution
  - gnome-tour
  - setroubleshoot
  - totem
  - yelp

baseos:
  - tmux

appstream:
  - cargo
  - clang
  - cmake
  - golang
  - podman
  - python3-pip

epel:
  # foliate grub-customizer htop
  - file-roller
  - inxi
  - mediainfo
  - neofetch
  - ntfs-3g
  - pass
  - perl-Image-ExifTool
  - speedtest-cli
  - transmission

crb:
  - inxi

rpmfusion_free_el9:
  - vlc

rpmfusion_nonfree_el9:
  - steam

desired_el9_pkgs: "{{ appstream | union(rpmfusion_free_el9) | union(epel) | union(yandex_disk) | union(vscode) | unique }}"
